global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ai-object-counter"
    static_configs:
      - targets: ["host.docker.internal:8000"] # Backend API
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s
